name: Android CI
run-name: ${{github.workflow}} - ${{vars.TAG}} - ${{github.sha}}

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

#    - name: Mask password
#      run: |
#        INP_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
#        echo ::add-mask::$INP_PASSWORD
#        echo PASSWORD="$INP_PASSWORD" >> $GITHUB_ENV

 #   - name: Decrypt secrets
 #     run: |
 #       echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties.asc
 #       gpg -d --passphrase "${PASSWORD}" --batch local.properties.asc > local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: List output APK files
      run: ls -la app/build/outputs/apk/debug/

    - uses: actions/upload-artifact@v4
      with:
        name: Debug APK files
        path: app/build/outputs/apk/debug/*.apk
